### ISSUE TITLE
El modelo no funciona -5 putnos tarao

### ISSUE THREAD

**Issue by AngelloFD** [AdrianMPC/ui_paralela#1]
RE: @AdrianMPC 
@AldhairOD 

Absolutamente nada que ver la transcripción y por alguna razón está obsesionado con skidibi toilet. Por favor, eliminar cuenta.

Saludos cordiales,
Tuvi

**Comment by AdrianMPC** [comment]
Falta de respeto la verdad, poca profesionalidad
Debería estar avergonzado con sigo mismo

Cerrando hilo
